apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: app3-workload
  description: App3 worker App
  tags:
    - java
    - nosql
  annotations:
    'backstage.io/kubernetes-label-selector': 'app=app3-workload-00001'
    'backstage.io/techdocs-ref': dir:.
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: app3-workload-system
  #dependsOn: [Component:yelb-db]